//
//  StringManager.swift
//  Essentials 7
//
//  Created by Nickelfox on 29/09/21.
//  Copyright © 2021 IFSTA. All rights reserved.
//
// swiftlint:disable all

//import Foundation
//import UIKit
//
//// static labels or keys in app for changing translation(App Language)
//enum Text {
//    case courses
//    case interactiveCourse
//    case interactiveCourses
//    case chapter
//    case buyAll
//    case subParts
//    case part
//    case screens
//    case yes
//    case no
//    case ok
//    case oops
//    case delete
//    case isDeleted
//    case cancel
//    case areYouSureYouWantToGoBack
//    
//    case inAppPurchase
//    case dismiss
//    case error
//    case noIAPProductProductIdentifiersFound
//    case noIAPFound
//    case unableToFetchIAPPurchaseProduct
//    case iapProcessCancelled
//    case purchase
//    case purchaseComplete
//    case unlock
//    case restorePurchases
//    case productIdentifierNotAvailableDummyPurchaseTesting
//    case thereNoPurchasedRestore
//    case previousIAPRestored
//    case buyingItemNotPossible
//    case productIdentifierIsNotAvailable
//    case previousPurchasesRestored
//    case unknownError
//    
//    case audioBook
//    case audiobook
//    case allAudiobooks
//    case downloads
//    case download
//    case downloadAll
//    case cancelDownload
//    case cancelDownloads
//    case downloadSelected
//    case bookmark
//    case bookmarks
//    case audiobooks
//    case notes
//    case noNotesYet
//    case addNote
//    case noAudioFound
//    case noAudioYet
//    case speed
//    case narrationSpeed
//    case areYouSureDeleteChapter
//    case youCanDownloadAgain
//    case addANoteAt
//    case continuePlaying
//    case deleteAll
//    case deleteSelected
//    case addBookmark
//    case removeBookmark
//    case searchAudioPlaceHolder
//    case removeFromQueue
//    case addToQueue
//    case currentlyNoAudiobookAvailableOfflineToDelete
//    case noBookmarksYet
//    case noDownloadsYet
//    case deleteChapter
//    case deleteChapterMessage
//    case connectInternetMessage
//    case noInternet
//    case bookmarkRemoved
//    case bookmarked
//    case downloadSuccessful
//    case emptyBookmarkTitle
//    case repeatedTimeNote
//    case repeatedMessageNote
//    
//
//    case videos
//    case video
//    case continueWatching
//    case allVideos
//    case skill
//    case skillVideos
//    case otherSkills
//    case note
//    case step
//    case noVideo
//    case noVideoFound
//    case searchVideoPlaceHolder
//    case downloadIsInProgress
//    case successfullyDeleted
//    case filesDeleted
//    
//    case home
//    case about
//    case downloadableOffline
//    case fullySearchableText
//    case findMoreEBooksAt
//    case checkOutEBookEssentialsEdition
//    case learnMore
//    case welcomeText
//    case welcome
//    case recentResults
//    case ebookName
//    case offlineDownload
//    case edition
//    case eBookForEssentials
//    case flashcards
//    case aboutUsHomeDescription
//    case coursesHomeDescription
//    case audiobookHomeDescription
//    case examPrepHomeDescription
//    case videoHomeDescription
//    case identifyHomeDescription
//    case flashcardHomeDescription
//    
//    case examPrep
//    case practiceExam
//    case takePracticeExam
//    case reviewMyStudyDeck
//    case viewReports
//    case clearStudyDeck
//    case clearTestResults
//    case noQuestionsStudyDeck
//    case noTestResults
//    case exam
//    case exams
//    case questions
//    case question
//    case next
//    case examSettings
//    case immediateFeedbackForAllAnswers
//    case studyDeckForIncorrectAnswers
//    case enableImmediateFeedbackForAllAnswers
//    case enableStudyDeckForIncorrectAnswers
//    case selectNumberOfAttempts
//    case startExam
//    case skip
//    case addToStudyDeck
//    case addedToStudyDeck
//    case attemptsLeft
//    case exit
//    case scoreAndExit
//    case exitWithoutScoring
//    case result
//    case correct
//    case incorrect
//    case skipped
//    case areYouSureYouWantToFinishTheExam
//    case selectExams
//    case selectAll
//    case allSelected
//    case unselectAll
//    case selected
//    case selectedCaps
//    case howAreResultsCalculated
//    case thisFormulaIsUsedToCalculateResults
//    case totalNumberOfCorrectlyAnsweredChapter
//    case progressOfAChapter
//    case totalNumberOfQuestionsChapter
//    case percentageRule
//    case clearAllTestResults
//    case reportClearedForAllChapters
//    case noReportsAvailable
//    case reset
//    case removeAllQuestionsFromStudyDeck
//    case removedAllchaptersFromStudyDeck
//    case noQuestionsAreInStudyDeck
//    case checkResults
//    case exitWithoutScore
//    case studyDeck
//    case isDownloaded
//    case min
//    case max
//    case of
//    case finish
//    
//    case identify
//    case containerIdentification
//    case remainingQuestions
//    case letsBegin
//    case resetProgress
//    case toolIdentification
//    case areYouSureYouWantToExit
//    case congratulationMessage
//    
//    case more
//    case language
//    case languageSelected
//    case languageSettings
//    case englishUS
//    case english
//    case spanish
//    case chooseALanguage
//    case allLanguages
//    case switchLanguage
//    case switchingLanguageWillStopDownloadsAndAudiobook
//    case updateRequired
//    case settings
//    
//    // action to get the keys value as per language selected ie: search "technical_desc" for different
//    // languages in  Resources -> Localizable.string file
//    
//    func localize() -> String {
//        switch self {
//        case .courses:
//            return "Chapters".localized
//        case .interactiveCourse:
//            return "interactiveCourse".localized
//        case .interactiveCourses:
//            return "interactiveCourses".localized
//        case .chapter:
//            return "chapter".localized
//        case .buyAll:
//            return "buyAll".localized
//        case .subParts:
//            return "subParts".localized
//        case .part:
//            return "part".localized
//        case .screens:
//            return "screens".localized
//        case .yes:
//            return "yes".localized
//        case .no:
//            return "no".localized
//        case .ok:
//            return "ok".localized
//        case .oops:
//            return "oops".localized
//        case .delete:
//            return "delete".localized
//        case .isDeleted:
//            return "isDeleted".localized
//        case .cancel:
//            return "cancel".localized
//        case .areYouSureYouWantToGoBack:
//            return "areYouSureYouWantToGoBack".localized
//        case .inAppPurchase:
//            return "inAppPurchase".localized
//        case .dismiss:
//            return "dismiss".localized
//        case .error:
//            return "error".localized
//        case .noIAPProductProductIdentifiersFound:
//            return "noIAPProductProductIdentifiersFound".localized
//        case .noIAPFound:
//            return "noIAPFound".localized
//        case .unableToFetchIAPPurchaseProduct:
//            return "unableToFetchIAPPurchaseProduct".localized
//        case .iapProcessCancelled:
//            return "iapProcessCancelled".localized
//        case .purchase:
//            return "purchase".localized
//        case .purchaseComplete:
//            return "purchaseComplete".localized
//        case .unlock:
//            return "unlock".localized
//        case .restorePurchases:
//            return "restorePurchases".localized
//        case .productIdentifierNotAvailableDummyPurchaseTesting:
//            return "productIdentifierNotAvailableDummyPurchaseTesting".localized
//        case .thereNoPurchasedRestore:
//            return "thereNoPurchasedRestore".localized
//        case .previousIAPRestored:
//            return "previousIAPRestored".localized
//        case .buyingItemNotPossible:
//            return "buyingItemNotPossible".localized
//        case .productIdentifierIsNotAvailable:
//            return "productIdentifierIsNotAvailable".localized
//        case .previousPurchasesRestored:
//            return "previousPurchasesRestored".localized
//        case .unknownError:
//            return "unknownError".localized
//            
//        case .audioBook:
//            return "audioBook".localized
//        case .audiobook:
//            return "audiobook".localized
//        case .allAudiobooks:
//            return "allAudiobooks".localized
//        case .downloads:
//            return "downloads".localized
//        case .download:
//            return "download".localized
//        case .downloadAll:
//            return "downloadAll".localized
//        case .cancelDownload:
//            return "cancelDownload".localized
//        case .cancelDownloads:
//            return "cancelDownloads".localized
//        case .downloadSelected:
//            return "downloadSelected".localized
//        case .bookmark:
//            return "bookmark".localized
//        case .bookmarks:
//            return "bookmarks".localized
//        case .audiobooks:
//            return "audiobooks".localized
//        case .notes:
//            return "notes".localized
//        case .noNotesYet:
//            return "noNotesYet".localized
//        case .addNote:
//            return "addNote".localized
//        case .noAudioFound:
//            return "noAudioFound".localized
//        case .noAudioYet:
//            return "noAudioYet".localized
//        case .speed:
//            return "speed".localized
//        case .narrationSpeed:
//            return "narrationSpeed".localized
//        case .areYouSureDeleteChapter:
//            return "areYouSureDeleteChapter".localized
//        case .youCanDownloadAgain:
//            return "youCanDownloadAgain".localized
//        case .addANoteAt:
//            return "addANoteAt".localized
//        case .continuePlaying:
//            return "continuePlaying".localized
//        case .deleteAll:
//            return "deleteAll".localized
//        case .deleteSelected:
//            return "deleteSelected".localized
//        case .addBookmark:
//            return "addBookmark".localized
//        case .removeBookmark:
//            return "removeBookmark".localized
//        case .searchAudioPlaceHolder:
//            return "searchAudioPlaceHolder".localized
//        case .removeFromQueue:
//            return "removeFromQueue".localized
//        case .addToQueue:
//            return "addToQueue".localized
//        case .currentlyNoAudiobookAvailableOfflineToDelete:
//            return "currentlyNoAudiobookAvailableOfflineToDelete".localized
//        case .noBookmarksYet:
//            return "noBookmarksYet".localized
//        case .noDownloadsYet:
//            return "noDownloadsYet".localized
//        case .deleteChapter:
//            return "deleteChapter".localized
//        case .deleteChapterMessage:
//            return "deleteChapterMessage".localized
//        case .connectInternetMessage:
//            return "connectInternetMessage".localized
//        case .noInternet:
//            return "noInternet".localized
//        case .bookmarkRemoved:
//            return "bookmarkRemoved".localized
//        case .bookmarked:
//            return "bookmarked".localized
//        case .downloadSuccessful:
//            return "downloadSuccessful".localized
//        case .emptyBookmarkTitle:
//            return "emptyBookmarkTitle".localized
//        case .repeatedTimeNote:
//            return "repeatedTimeNote".localized
//        case .repeatedMessageNote:
//            return "repeatedMessageNote".localized
//        case .videos:
//            return "videos".localized
//        case .video:
//            return "video".localized
//        case .continueWatching:
//            return "continueWatching".localized
//        case .allVideos:
//            return "allVideos".localized
//        case .skill:
//            return "skill".localized
//        case .skillVideos:
//            return "skillVideos".localized
//        case .otherSkills:
//            return "otherSkills".localized
//        case .note:
//            return "note".localized
//        case .step:
//            return "step".localized
//        case .noVideo:
//            return "noVideo".localized
//        case .noVideoFound:
//            return "noVideoFound".localized
//        case .searchVideoPlaceHolder:
//            return "searchVideoPlaceHolder".localized
//        case .downloadIsInProgress:
//            return "downloadIsInProgress".localized
//        case .successfullyDeleted:
//            return "successfullyDeleted".localized
//        case .filesDeleted:
//            return "filesDeleted".localized
//            
//        case .home:
//            return "home".localized
//        case .about:
//            return "about".localized
//        case .downloadableOffline:
//            return "downloadableOffline".localized
//        case .fullySearchableText:
//            return "fullySearchableText".localized
//        case .findMoreEBooksAt:
//            return "findMoreEBooksAt".localized
//        case .checkOutEBookEssentialsEdition:
//            return "checkOutEBookEssentialsEdition".localized
//        case .learnMore:
//            return "learnMore".localized
//        case .welcomeText:
//            return "welcomeText".localized
//        case .welcome:
//            return "welcome".localized
//        case .recentResults:
//            return "recentResults".localized
//        case .ebookName:
//            return "ebookName".localized
//        case .offlineDownload:
//            return "offlineDownload".localized
//        case .edition:
//            return "edition".localized
//        case .eBookForEssentials:
//            return "eBookForEssentials".localized
//        case .flashcards:
//            return "flashcards".localized
//        case .aboutUsHomeDescription:
//            return "aboutUsHomeDescription".localized
//        case .coursesHomeDescription:
//            return "coursesHomeDescription".localized
//        case .audiobookHomeDescription:
//            return "audiobookHomeDescription".localized
//        case .examPrepHomeDescription:
//            return "examPrepHomeDescription".localized
//        case .videoHomeDescription:
//            return "videoHomeDescription".localized
//        case .identifyHomeDescription:
//            return "identifyHomeDescription".localized
//        case .flashcardHomeDescription:
//            return "flashcardHomeDescription".localized
//            
//        case .examPrep:
//            return "examPrep".localized
//        case .practiceExam:
//            return "practiceExam".localized
//        case .takePracticeExam:
//            return "takePracticeExam".localized
//        case .reviewMyStudyDeck:
//            return "reviewMyStudyDeck".localized
//        case .viewReports:
//            return "viewReports".localized
//        case .clearStudyDeck:
//            return "clearStudyDeck".localized
//        case .clearTestResults:
//            return "clearTestResults".localized
//        case .noQuestionsStudyDeck:
//            return "noQuestionsStudyDeck".localized
//        case .noTestResults:
//            return "noTestResults".localized
//        case .exam:
//            return "exam".localized
//        case .exams:
//            return "exams".localized
//        case .questions:
//            return "questions".localized
//        case .question:
//            return "question".localized
//        case .next:
//            return "next".localized
//        case .examSettings:
//            return "examSettings".localized
//        case .immediateFeedbackForAllAnswers:
//            return "immediateFeedbackForAllAnswers".localized
//        case .studyDeckForIncorrectAnswers:
//            return "studyDeckForIncorrectAnswers".localized
//        case .enableImmediateFeedbackForAllAnswers:
//            return "enableImmediateFeedbackForAllAnswers".localized
//        case .enableStudyDeckForIncorrectAnswers:
//            return "enableStudyDeckForIncorrectAnswers".localized
//        case .selectNumberOfAttempts:
//            return "selectNumberOfAttempts".localized
//        case .startExam:
//            return "startExam".localized
//        case .skip:
//            return "skip".localized
//        case .addToStudyDeck:
//            return "addToStudyDeck".localized
//        case .addedToStudyDeck:
//            return "addedToStudyDeck".localized
//        case .attemptsLeft:
//            return "attemptsLeft".localized
//        case .exit:
//            return "exit".localized
//        case .scoreAndExit:
//            return "scoreAndExit".localized
//        case .exitWithoutScoring:
//            return "exitWithoutScoring".localized
//        case .result:
//            return "result".localized
//        case .correct:
//            return "correct".localized
//        case .incorrect:
//            return "incorrect".localized
//        case .skipped:
//            return "skipped".localized
//        case .areYouSureYouWantToFinishTheExam:
//            return "areYouSureYouWantToFinishTheExam".localized
//        case .selectExams:
//            return "selectExams".localized
//        case .selectAll:
//            return "selectAll".localized
//        case .allSelected:
//            return "allSelected".localized
//        case .unselectAll:
//            return "unselectAll".localized
//        case .selected:
//            return "selected".localized
//        case .selectedCaps:
//            return "selectedCaps".localized
//        case .howAreResultsCalculated:
//            return "howAreResultsCalculated".localized
//        case .thisFormulaIsUsedToCalculateResults:
//            return "thisFormulaIsUsedToCalculateResults".localized
//        case .totalNumberOfCorrectlyAnsweredChapter:
//            return "totalNumberOfCorrectlyAnsweredChapter".localized
//        case .progressOfAChapter:
//            return "progressOfAChapter".localized
//        case .totalNumberOfQuestionsChapter:
//            return "totalNumberOfQuestionsChapter".localized
//        case .percentageRule:
//            return "percentageRule".localized
//        case .clearAllTestResults:
//            return "clearAllTestResults".localized
//        case .reportClearedForAllChapters:
//            return "reportClearedForAllChapters".localized
//        case .noReportsAvailable:
//            return "noReportsAvailable".localized
//        case .reset:
//            return "reset".localized
//        case .removeAllQuestionsFromStudyDeck:
//            return "removeAllQuestionsFromStudyDeck".localized
//        case .removedAllchaptersFromStudyDeck:
//            return "removedAllchaptersFromStudyDeck".localized
//        case .noQuestionsAreInStudyDeck:
//            return "noQuestionsAreInStudyDeck".localized
//        case .checkResults:
//            return "checkResults".localized
//        case .exitWithoutScore:
//            return "exitWithoutScore".localized
//        case .studyDeck:
//            return "studyDeck".localized
//        case .isDownloaded:
//            return "isDownloaded".localized
//        case .min:
//            return "min".localized
//        case .max:
//            return "max".localized
//        case .of:
//            return "of".localized
//        case .finish:
//            return "finish".localized
//            
//            
//            
//            
//        case .identify:
//            return "identify".localized
//        case .containerIdentification:
//            return "containerIdentification".localized
//        case .remainingQuestions:
//            return "remainingQuestions".localized
//        case .letsBegin:
//            return "letsBegin".localized
//        case .resetProgress:
//            return "resetProgress".localized
//        case .toolIdentification:
//            return "toolIdentification".localized
//        case .areYouSureYouWantToExit:
//            return "areYouSureYouWantToExit".localized
//        case .congratulationMessage:
//            return "congratulationMessage".localized
//            
//            
//        case .more:
//            return "more".localized
//        case .language:
//            return "language".localized
//        case .languageSelected:
//            return "languageSelected".localized
//        case .languageSettings:
//            return "languageSettings".localized
//        case .englishUS:
//            return "englishUS".localized
//        case .english:
//            return "english".localized
//        case .spanish:
//            return "spanish".localized
//        case .chooseALanguage:
//            return "chooseALanguage".localized
//        case .allLanguages:
//            return "allLanguages".localized
//        case .switchLanguage:
//            return "switchLanguage".localized
//        case .switchingLanguageWillStopDownloadsAndAudiobook:
//            return "switchingLanguageWillStopDownloadsAndAudiobook".localized
//        case .settings:
//            return "settings".localized
//        case .updateRequired:
//            return "updateRequired".localized
//        }
//    }
//}
//
//extension String {
//    var localized: String {
//        guard let path = Bundle.main.path(forResource: UserDefaults.languageCode, ofType: "lproj") else {return self}
//        let bundle = Bundle(path: path)
//        return NSLocalizedString(self, tableName: nil, bundle: bundle!, value: "", comment: "")
////        return NSLocalizedString(self, comment: "")
//    }
//    
//}
//// swiftlint:enable all
